/* Reharm: the moves as data. Pure, no DOM. Tested by tests/theory.test.js
   Each move: a short progression before and after, written like PROGS ([letter steps, semitones, quality, degree, bass degree]),
   the positions you play (slots), and a card that says what it is, why it works and where you hear it. */
const RHSRC={
  secdom:'https://pianowithjonny.com/piano-lessons/secondary-dominants-the-complete-guide/',
  passing:'https://pianowithjonny.com/piano-lessons/passing-chords-5-levels-beginner-to-pro/',
  tritone:'https://learnmusictheory.net/pdfs/pdffiles/04-09-introductiontoreharmonization.pdf',
  iiV:'https://www.thejazzpianosite.com/jazz-piano-lessons/jazz-reharmonization/ii-v-substitution/',
  cadence:'https://www.learnjazzstandards.com/blog/musical-cadences/',
  reharm:'https://en.wikipedia.org/wiki/Harmonization',
};
const I_=[0,0,'maj7','I'], II_=[1,2,'min7','II'], III_=[2,4,'min7','III'], IV_=[3,5,'maj7','IV'], V_=[4,7,'dom7','V'], VI_=[5,9,'min7','VI'];
const RH=(id,name,tier,o)=>({id,name,tier,...o});
const REHARM_MOVES=[
  // ---------------- Tier 1: everyday moves ----------------
  RH('secdom','Secondary dominant',1,{what:'Put a dominant 7th in front of a chord to point at it, as if that chord were briefly home.',
    why:'A7 is the V of Dm. Its C♯ is a leading note that pulls up to D, so IIm7 arrives with a real pull instead of just showing up.',
    where:'Everywhere. The VI7 in the I–VI–II–V turnaround.',ask:'Make VIm7 a dominant that points at IIm7',
    before:[I_,VI_,II_,V_],after:[I_,[5,9,'dom7','VI'],II_,V_],slots:[1],src:RHSRC.secdom}),
  RH('addii','Add the ii',1,{what:'Put the ii chord right before a dominant, so V7 becomes IIm7–V7.',
    why:'Two chords leading in is smoother than one: IIm7 moves to V7 by a 4th, the strongest root motion there is.',
    where:'The ii–V–I, the most common move in jazz. It works in front of any dominant, secondary ones too.',ask:'Add the ii in front of V7',
    before:[I_,V_,I_],after:[I_,II_,V_,I_],slots:[1],src:RHSRC.iiV}),
  RH('ivv','IV/V instead of V7',1,{what:'Swap V7 for the IV chord over the V bass note: F/G in C.',
    why:'F/G keeps G in the bass but leaves out the 3rd (B), so the pull home is softer and more open. It is the same sound as G9sus4.',
    where:'All over J-pop, gospel and city pop: the IV/V option in Royal Road and Passing diminished.',ask:'Replace V7 with IV over the V bass',
    before:[II_,V_,I_],after:[II_,[3,5,'maj_2','IV','V'],I_],slots:[1]}),
  RH('minoriv','Minor iv',1,{what:'After IV, make it minor before going home: F → Fm6 → C.',
    why:'Fm borrows A♭ from C minor. A♭ falls a half step to G, a bittersweet sigh into the I.',
    where:'J-pop ballads; the Minor iv progression (サブドミナントマイナー).',ask:'Make the IV minor before going home',
    before:[IV_,I_],after:[IV_,[3,5,'min6','IV'],I_],slots:[1],src:RHSRC.reharm}),
  RH('passdim','Passing diminished',1,{what:'Slide a diminished 7th between two chords a whole step apart: C → C♯°7 → Dm7.',
    why:'C♯°7 is A7♭9 without its root, a secondary dominant in disguise, and the bass climbs by half steps.',
    where:'Gospel, city pop and J-pop; the ♯IV°7 in the Passing diminished progression.',ask:'Fill the gap between I and IIm7 with a passing chord',
    before:[I_,II_,V_],after:[I_,[0,1,'dim7','♯I'],II_,V_],slots:[1],src:RHSRC.passing}),
  RH('deceptive','Deceptive cadence',1,{what:'Resolve V7 to VIm7 instead of I.',
    why:'VIm7 shares notes with I (C, E and G), so it sounds like home but sadder, and the phrase keeps going instead of ending.',
    where:'The end of a verse that wants one more line; ballads.',ask:'Fake the ending: resolve V7 somewhere else',
    before:[II_,V_,I_],after:[II_,V_,VI_],slots:[2],src:RHSRC.cadence}),
  RH('sus','Sus before the 3rd',1,{what:'Delay the V7: play V7sus4 first, then V7.',
    why:'The sus4 (C over G) holds the 3rd back; letting it fall to B makes a small resolution before the big one.',
    where:'Gospel and pop endings, film-score cadences.',ask:'Hold the V back with a sus chord first',
    before:[II_,V_,I_],after:[II_,[4,7,'sus7','V'],V_,I_],slots:[1]}),
  RH('iiiForI','I to IIIm7',1,{what:'Replace the second bar of I with IIIm7.',
    why:'Em7 shares three notes with Cmaj7 (E, G and B), so it keeps the home sound while the bass moves, setting up III–VI–II–V.',
    where:'City pop turnarounds; the III–VI–II–V progression.',ask:'Swap the second bar of I for a chord that shares its notes',
    before:[I_,I_,II_,V_],after:[I_,III_,II_,V_],slots:[1],src:RHSRC.reharm}),
  // ---------------- Tier 2: colour and motion ----------------
  RH('tritone','Tritone sub',2,{what:'Replace V7 with the dominant a tritone away: D♭7 for G7.',
    why:'G7 and D♭7 share the same 3rd and 7th (B and F, swapped), so the pull home stays, but the bass slides down by half step.',
    where:'Jazz everywhere, neo-soul, Jacob Collier-style reharms.',ask:'Replace V7 with its tritone sub',
    before:[II_,V_,I_],after:[II_,[1,1,'dom7','♭II'],I_],slots:[1],src:RHSRC.tritone}),
  RH('backdoor','Backdoor ii–V',2,{what:'Come home from the flat side: IVm7 → ♭VII7 → I instead of IIm7 → V7 → I.',
    why:'B♭7 in C has A♭ and D in it; A♭ falls to G and D steps up to E, a warm, slightly bluesy way into the I.',
    where:'Standards, gospel, and the Backdoor progression.',ask:'Replace the ii–V with the backdoor ii–V',
    before:[II_,V_,I_],after:[[3,5,'min7','IV'],[6,10,'dom7','♭VII'],I_],slots:[0,1],src:RHSRC.iiV}),
  RH('borrowed','Borrowed ♭VI and ♭VII',2,{what:'Approach I from the flat side with two borrowed major chords: A♭maj7 → B♭7 → C.',
    why:'Both come from C minor. The roots climb by whole steps into I, a bright, triumphant arrival: the video-game victory sound.',
    where:'Anime and game endings, rock ballads, J-pop final choruses.',ask:'Swap IV and V for the two borrowed chords',
    before:[IV_,V_,I_],after:[[5,8,'maj7','♭VI'],[6,10,'dom7','♭VII'],I_],slots:[0,1],src:RHSRC.reharm}),
  RH('iii7','III7 instead of IIIm7',2,{what:'Make the IIIm7 in the Royal Road a dominant: III7, pointing at VIm7.',
    why:'E7 is the V of Am. Its G♯ leans into A, which turns the Royal Road into the Just the Two of Us sound.',
    where:'Just the Two of Us (丸サ進行) and countless J-pop choruses.',ask:'Turn the IIIm7 into a dominant that points at VIm7',
    before:[IV_,V_,III_,VI_],after:[IV_,V_,[2,4,'dom7','III'],VI_],slots:[2],src:RHSRC.secdom}),
  RH('slip','Chromatic approach chord',2,{what:'Approach a chord from a half step above with the same chord type: E♭m7 → Dm7.',
    why:'Every note slides down a half step into the target: the smoothest possible way in, a slick slip into place.',
    where:'Neo-soul, gospel, and any time a chord needs a lead-in.',ask:'Slip into IIm7 from a half step above',
    before:[I_,II_,V_],after:[I_,[2,3,'min7','♭III'],II_,V_],slots:[1],src:RHSRC.reharm}),
  RH('bassdown','Descending bass line',2,{what:'Keep the chords in the key but walk the bass down by step with inversions: C → G/B → Am → C/G.',
    why:'Nothing new harmonically: G/B is still G, C/G is still C. Putting different chord notes in the bass turns the bass part into a melody of its own.',
    where:'Everywhere in J-pop and ballads; the Canon progression is built on it.',ask:'Use inversions so the bass walks down by step',
    before:[[0,0,'maj','I'],[4,7,'maj','V'],[5,9,'min','VI'],[0,0,'maj','I']],after:[[0,0,'maj','I'],[4,7,'maj_3','V','VII'],[5,9,'min','VI'],[0,0,'maj_5','I','V']],slots:[1,3],exact:true,src:RHSRC.reharm}),
  RH('cliche','Minor line cliché',2,{what:'Hold a minor chord and move one inner note down by half steps: Am → Am(maj7) → Am7 → Am6.',
    why:'The root stays put while a single voice falls A, G♯, G, F♯. One chord on paper becomes four bars of motion.',
    where:'Ballads, Bond themes, J-pop minor verses; the Minor line cliché progression.',ask:'Keep the minor chord and walk its top note down by half steps',
    minor:true,before:[[0,0,'min','I'],[0,0,'min','I'],[0,0,'min','I'],[0,0,'min','I']],after:[[0,0,'min','I'],[0,0,'mmaj7','I'],[0,0,'min7','I'],[0,0,'min6','I']],slots:[1,2,3],exact:true}),
  RH('chain','ii–V chain',2,{what:'Give a chord its own ii–V in front: Cmaj7 → Em7♭5 → A7 → Dm7 → G7.',
    why:'Em7♭5–A7 is the ii–V of D minor, so Dm7 arrives like a little key of its own. Chained, every chord gets pulled to the next one.',
    where:'Standards, gospel turnarounds, any bar that needs more motion.',ask:'Put the ii–V of IIm7 in front of it',
    before:[I_,II_,V_],after:[I_,[2,4,'hdim','III'],[5,9,'dom7','VI'],II_,V_],slots:[1,2],src:RHSRC.iiV}),
  RH('tritoneiiV','Tritone sub of the whole ii–V',2,{what:'Tritone-sub the ii as well as the V: A♭m7 → D♭7 → C instead of Dm7 → G7 → C.',
    why:'D♭7 is the tritone sub of G7, and A♭m7 is its own ii, so the whole approach slides down from a half step above.',
    where:'Bebop and modern jazz; any ii–V you want to colour.',ask:'Replace the ii–V with the ii–V a tritone away',
    before:[II_,V_,I_],after:[[5,8,'min7','♭VI'],[1,1,'dom7','♭II'],I_],slots:[0,1],src:RHSRC.iiV}),
  RH('pedal','Pedal point',2,{what:'Hold the root in the bass while the chords above it change: C → F/C → B♭/C → C.',
    why:'The held bass note glues the chords together; the tension comes from chords that clash with it and resolve back over it.',
    where:'Gospel endings, intros and outros, anime ballads.',ask:'Keep the I in the bass under the moving chords',
    before:[[0,0,'maj','I'],[3,5,'maj','IV'],[6,10,'maj','♭VII'],[0,0,'maj','I']],after:[[0,0,'maj','I'],[3,5,'maj_5','IV','I'],[6,10,'maj_2','♭VII','I'],[0,0,'maj','I']],slots:[1,2],exact:true}),
  RH('neapolitan','♭IImaj7 for IIm7',2,{what:'Replace the ii with the major 7 chord a half step above the root: D♭maj7 → G7 → C.',
    why:'D♭maj7 is borrowed from C minor (the Neapolitan chord). Its D♭ falls to C and its A♭ to G, a dark, plush way into the V.',
    where:'Film and game scores, R&B ballads.',ask:'Replace IIm7 with the major 7 chord a half step above I',
    before:[II_,V_,I_],after:[[1,1,'maj7','♭II'],V_,I_],slots:[0],src:RHSRC.reharm}),
  RH('flat3','Borrowed ♭IIImaj7',2,{what:'Swap IIIm7 for E♭maj7, borrowed from C minor.',
    why:'E♭maj7 keeps G and D from the key but brings in E♭ and B♭ from C minor: a sudden change of light just before IV.',
    where:'City pop, J-pop pre-choruses, rock ballads.',ask:'Replace IIIm7 with the borrowed major 7 a half step lower',
    before:[I_,III_,IV_,V_],after:[I_,[2,3,'maj7','♭III'],IV_,V_],slots:[1],src:RHSRC.reharm}),
  RH('flat6','V to ♭VI',2,{what:'Resolve V7 to A♭maj7 instead of C: a deceptive cadence with a borrowed chord.',
    why:'A♭maj7 contains C and G, so it sounds close to home, but its A♭ and E♭ come from C minor: the ear expects I and gets a warm surprise instead.',
    where:'The big lift into a final chorus; ballads.',ask:'Fake the ending onto the borrowed ♭VI',
    before:[II_,V_,I_],after:[II_,V_,[5,8,'maj7','♭VI']],slots:[2],src:RHSRC.cadence}),
  RH('ctdim','Common-tone diminished',2,{what:'Decorate a chord with the diminished 7th that shares its root: C → C°7 → C.',
    why:'The root C never moves; the other three notes lean out by a half step and come back, like the chord taking a breath.',
    where:'Old-school ballads, gospel, stride piano.',ask:'Decorate I with the diminished chord that keeps its root',
    before:[I_,I_],after:[I_,[0,0,'dim7','I'],I_],slots:[1],src:RHSRC.passing}),
  RH('ladybird','Lady Bird turnaround',2,{what:'Replace I–VI–II–V with Cmaj7 → E♭7 → A♭maj7 → D♭maj7, Tadd Dameron\'s turnaround.',
    why:'E♭7 is the tritone sub of A7 (the VI7), A♭maj7 is borrowed from C minor in place of Dm7, and D♭maj7 stands in for G7 a tritone away. The bass falls through rich, unexpected chords and still lands on C.',
    where:'Bebop tunes (Lady Bird, Half Nelson), modern jazz endings.',ask:'Replace the turnaround with the Lady Bird turnaround',
    before:[I_,VI_,II_,V_],after:[I_,[2,3,'dom7','♭III'],[5,8,'maj7','♭VI'],[1,1,'maj7','♭II']],slots:[1,2,3],src:RHSRC.iiV}),
  // ---------------- Tier 3: the modern sound ----------------
  RH('coltrane','Coltrane changes',3,{what:'Fill a ii–V–I with keys a major third apart: Dm7 → E♭7 → A♭maj7 → B7 → Emaj7 → G7 → Cmaj7.',
    why:'C, A♭ and E divide the octave into three equal parts. Each key gets its own V7, so the music tours three key centres and still lands on C.',
    where:'Giant Steps, Countdown, and modern jazz reharms.',ask:'Tour the three key centres a major third apart on the way to I',
    before:[II_,V_,I_],after:[II_,[2,3,'dom7','♭III'],[5,8,'maj7','♭VI'],[6,11,'dom7','VII'],[2,4,'maj7','III'],V_,I_],slots:[1,2,3,4],src:'https://en.wikipedia.org/wiki/Coltrane_changes'}),
  RH('mediant','Chromatic mediant',3,{what:'Jump to the major 7 chord a major third away: Cmaj7 → Emaj7 → Fmaj7.',
    why:'C and E major share one note (E) and differ by two half steps. The jump sounds cinematic, and Emaj7 slides a half step into Fmaj7.',
    where:'Film scores, Jacob Collier-style reharms, modern J-pop bridges.',ask:'Jump from I to the major 7 a major third up',
    before:[I_,I_,IV_],after:[I_,[2,4,'maj7','III'],IV_],slots:[1],src:'https://en.wikipedia.org/wiki/Chromatic_mediant'}),
  RH('constant','Constant structure',3,{what:'Use the same chord type on every root: Cmaj7 → Dmaj7 → Emaj7 → Fmaj7 instead of the diatonic chords.',
    why:'Keeping one shape and moving it around ignores the key on purpose. The melody of the roots carries it, with a floating, modern colour.',
    where:'Herbie Hancock, Bill Evans, neo-soul, modern J-pop ballads.',ask:'Keep the maj7 shape on each step up',
    before:[I_,II_,III_,IV_],after:[I_,[1,2,'maj7','II'],[2,4,'maj7','III'],IV_],slots:[1,2],exact:true,src:'https://www.berklee.edu/berklee-today/summer-2001/Reharmonization'}),
  RH('ust','Upper-structure triad',3,{what:'Play a major triad on the 2nd of a dominant over its shell: A major over G7 gives G13♯11.',
    why:'A, C♯ and E are the 9, ♯11 and 13 of G7, so one easy triad in the right hand turns a plain V7 into the bright Lydian dominant sound.',
    where:'Modern jazz, gospel, fusion; McCoy Tyner and Herbie Hancock voicings.',ask:'Turn V7 into the 7♯11 sound with a triad on its 2nd',
    before:[II_,V_,I_],after:[II_,[4,7,'d7s11','V'],I_],slots:[1],exact:true}),
  RH('quartal','Quartal (sus) reharm',3,{what:'Swap the ii–V–I for sus and quartal sounds: Dm11 → G7sus4 → C6/9.',
    why:'Stacked 4ths leave out the leading notes that pull the chords to each other, so the progression floats instead of pushing.',
    where:'Herbie Hancock, Maiden Voyage, neo-soul and fusion.',ask:'Replace each chord with its sus or quartal version',
    before:[II_,V_,I_],after:[[1,2,'min11','II'],[4,7,'sus7','V'],[0,0,'six9','I']],slots:[0,1,2],exact:true}),
  RH('negative','Negative harmony ii–V',3,{what:'Mirror the ii–V around the key\'s centre: Gm7 → Fm6 → C instead of Dm7 → G7 → C.',
    why:'Reflecting each note around the axis between E♭ and E turns G7 into Fm6 and Dm7 into Gm7. The pull to C stays, but it comes from below, dark and soft.',
    where:'Jacob Collier, film scores; the minor iv is its simplest form.',ask:'Replace the ii–V with its mirror image',
    before:[II_,V_,I_],after:[[4,7,'min7','V'],[3,5,'min6','IV'],I_],slots:[0,1],src:'https://en.wikipedia.org/wiki/Negative_harmony'}),
  RH('melody','Reharm a melody note',3,{what:'Under a held melody note C, play a chord where C becomes the 9th, 11th or 13th instead of the root.',
    why:'The same note sounds completely different over B♭maj7 (it\'s the 9), Gm7 (the 11) or E♭maj7 (the 13). Choosing the chord under the melody is most of real-world reharm.',
    where:'Every arrangement; how pianists make a simple melody sound rich.',ask:'Under the held C, play a chord where C is the 9, 11 or 13',
    before:[I_,I_],after:[I_,[6,10,'maj7','♭VII']],slots:[1],melody:0,
    alts:{1:[[6,10,'maj7','♭VII'],[4,7,'min7','V'],[2,3,'maj7','♭III'],[6,10,'maj9','♭VII'],[4,7,'min9','V']]}}),
];
const RHMOVE=Object.fromEntries(REHARM_MOVES.map(m=>[m.id,m]));
// Chord types that count for a slot: any member of the written chord's family
const RH_FAM={dom7:['dom7','dom9','dom13','d7b9','d7s9','alt','d7b13','d7s11'],min7:['min7','min9','min11'],maj7:['maj7','maj9','six','six9','mj7s11'],
  dim7:['dim7','dim'],min6:['min6','min7','min','mmaj7','min9'],sus7:['sus7'],maj_2:['maj_2'],hdim:['hdim','min7'],min11:['min11','min9']};
// exact moves (line clichés, constant structure...) want that exact chord type; the rest take any chord of the family
const rhAccepts=(q,exact)=>(exact?[q.id]:(RH_FAM[q.id]||[q.id])).map(id=>Q[id]);
const rhChords=(entries,keyPc,minor)=>progChords({ch:entries,minor:!!minor},keyPc,a=>a[0]);
// The chords that count at a slot: the written one, or any of the move's alternatives (melody reharm has several right answers)
const rhTargets=(m,slot,keyPc)=>m.alts&&m.alts[slot]?rhChords(m.alts[slot],keyPc,m.minor):[rhChords(m.after,keyPc,m.minor)[slot]];
